name: Deploy to Server

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Run tests
      run: |
        python -m pytest tests/ || echo "No tests found, skipping"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.SERVER_HOST }}
        username: ${{ secrets.SERVER_USER }}
        key: ${{ secrets.SERVER_SSH_KEY }}
        port: ${{ secrets.SERVER_PORT }}
        script: |
          # Переход в директорию проекта
          cd /var/QualityControlSuite
          
          # Сохранение конфигурации (если есть локальные настройки)
          if [ -f config/local_settings.yaml ]; then
            cp config/local_settings.yaml /tmp/qc_local_settings.yaml
          fi
          
          # Обновление кода из репозитория
          git fetch origin
          git reset --hard origin/main
          git pull origin main
          
          # Восстановление локальной конфигурации
          if [ -f /tmp/qc_local_settings.yaml ]; then
            cp /tmp/qc_local_settings.yaml config/local_settings.yaml
            rm /tmp/qc_local_settings.yaml
          fi
          
          # Обновление зависимостей в виртуальном окружении
          if [ ! -d "venv" ]; then
            python3 -m venv venv
          fi
          source venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          
          # Установка прав доступа
          chmod +x main.py
          chmod -R 755 /var/QualityControlSuite
          
          # Перезапуск сервиса (если используется systemd)
          sudo systemctl restart qualitycontrolsuite || echo "Service not configured yet"
          
          # Проверка nginx конфигурации
          sudo nginx -t && sudo systemctl reload nginx || echo "Nginx not configured yet"
          
          echo "Deployment completed successfully!"